<?php

/**
 * PluginDocomoMobileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDocomoMobileTable extends MobileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDocomoMobileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDocomoMobile');
    }
}