<?php

/**
 * PluginSoftbankMobile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJpMobile
 * @subpackage model
 * @author     YUKI Kaoru <yuki@yagni.jp>
 * @version    SVN: $Id$
 */
abstract class PluginSoftbankMobile extends BaseSoftbankMobile
{

}