<?php

/**
 * PluginSoftbankMobileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSoftbankMobileTable extends MobileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSoftbankMobileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSoftbankMobile');
    }
}